### ISSUE TITLE
[Suggestion] Consider using WSS instead of WS.

### ISSUE THREAD

**Issue by Valiantiam** [Kurble/Tutris9#1]
Currently it uses WS for websocket. This makes use of this project behind a reverse proxy with SSL protections difficult due to mixed content loading of the WS: connections.

**Comment by Kurble** [comment]
This will definitely be considered for the future, but I didn't have the time to figure it out yet.

**Comment by Valiantiam** [comment]
I did some looking into a solution for that as well. It might be a limitation of actix-web. Some more reading of documentation will hopefully lead to an answer.

**Comment by Kurble** [comment]
I've done some research and actix-web is perfectly capable of operating in SSL mode. Since all connections go through the main HTTP server you just have to run the HTTP server with SSL.
I'll probably have https/wss support ready very soon
