### ISSUE TITLE
Controls Guide

### ISSUE THREAD

**Issue by Valiantiam** [Kurble/Tutris9#3]
It could be useful to include, on the battle screen, or countdown screen, a simple breakdown of the controls.

![image](https://user-images.githubusercontent.com/5394853/54094560-d7a73080-436f-11e9-8b2a-12acdfb3dded.png)

Something along these lines comes to mind.

**Comment by Kurble** [comment]
There's going to be a "controls" submenu in the main menu, where you  can remap controls

**Comment by Valiantiam** [comment]
OH perfect, this can be closed ahead of that, thanks!
