### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by carlosmax3D** [Kurble/Tutris9#9]
Is someone maintaining this project?.

I tried to deploy but I got an error at running this command
RUST_BACKTRACE=full cargo web deploy --package tetris_client --release

thread 'main' panicked at /home/carlos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo_metadata-0.6.4/src/lib.rs:261:40:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5629ad174476 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
   1:     0x5629ad1a3ff0 - core::fmt::write::he40921d4802ce2ac
   2:     0x5629ad1702bf - std::io::Write::write_fmt::h5de5a4e7037c9b20
   3:     0x5629ad174254 - std::sys_common::backtrace::print::h11c067a88e3bdb22
   4:     0x5629ad175b37 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
   5:     0x5629ad175899 - std::panicking::default_hook::h1633e272b4150cf3
   6:     0x5629ad175fc8 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
   7:     0x5629ad175e69 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
   8:     0x5629ad174976 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
   9:     0x5629ad175bf4 - rust_begin_unwind
  10:     0x5629acb0e575 - core::panicking::panic_fmt::ha6effc2775a0749c
  11:     0x5629acb0e633 - core::panicking::panic::h44790a89027c670f
  12:     0x5629acb0e4c6 - core::option::unwrap_failed::hcb3a256a9f1ca882
  13:     0x5629acc8c124 - cargo_metadata::WorkspaceMember::version::haca6f19c9cc827bb
  14:     0x5629acbd41da - core::hash::BuildHasher::hash_one::h6f889b72e797e43e
  15:     0x5629acbff9d4 - hashbrown::map::HashMap<K,V,S,A>::insert::ha52751fcfdf31185
  16:     0x5629acbda90d - cargo_web::cargo_shim::CargoProject::new::h8c425434bfe4669e
  17:     0x5629acb25f9e - cargo_web::build::BuildArgs::load_project::hf132a8bdefec5003
  18:     0x5629acc450ea - cargo_web::cmd_deploy::command_deploy::habd8c558728ccda0
  19:     0x5629acb38ab9 - cargo_web::run::h49d87748a429b9d2
  20:     0x5629acb1b6ff - cargo_web::main::hcbd872a0d5993deb
  21:     0x5629acb19ed3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he5e9d84d034f409e
  22:     0x5629acb19ee9 - std::rt::lang_start::{{closure}}::h609668c4a0a7ecb2
  23:     0x5629ad169791 - std::rt::lang_start_internal::h4d236095b69a230b
  24:     0x5629acb1b8e5 - main
  25:     0x7fd991cafb8a - __libc_start_call_main
  26:     0x7fd991cafc4b - __libc_start_main@@GLIBC_2.34
  27:     0x5629acb0ed25 - _start
  28:                0x0 - <unknown

I'm using the latest updates.

**Comment by Kurble** [comment]
I don't have time to work on this project, but I'm open to review/merge any PR's that fix this issue

**Comment by carlosmax3D** [comment]
Don't worry, it seems like the error is because of old dependencies and also quicksilver is now deprecated so, to fix it we need to do a lot of refactor. thanks!
